[16.0][ADD] product_packaging_level_sellable
QuocDuong1306/product-attribute pull request #1
Opened 2023-07-27 10:48 UTC by QuocDuong1306

This module allows odoo users to set:

* Can be sold: On product packaging type model, this checkbox defines if product
  packagings from this particular type are available to be selected on sale
  order line.

2023-07-27 13:10 UTC, nilshamerlinck requested changes
I think you should also add a new column can be sold in the tree view

2023-07-27 13:10 UTC, nilshamerlinck commented on product_packaging_level_sellable/__manifest__.py
> +# Copyright 2020 Camptocamp SA
2023

2023-07-27 13:10 UTC, nilshamerlinck commented on product_packaging_level_sellable/models/product_packaging.py
> +# Copyright 2020 Camptocamp SA
2023

2023-07-27 13:10 UTC, nilshamerlinck commented on product_packaging_level_sellable/models/sale_order_line.py
> +
```suggestion
```

2023-07-27 13:10 UTC, nilshamerlinck commented on product_packaging_level_sellable/readme/CONFIGURE.rst
> +  packagings from this particular type are available to be selected on sale
```suggestion
* Can be sold: On product packaging level model, this checkbox defines if product
  packagings from this particular level are available to be selected on sale
```

2023-07-27 13:10 UTC, nilshamerlinck commented on product_packaging_level_sellable/tests/common.py
> +    def setUpClassPackagingType(cls):
```suggestion
    def setUpClassPackagingLevel(cls):
```

2023-07-27 13:10 UTC, nilshamerlinck commented on product_packaging_level_sellable/tests/test_packaging_level_can_be_sold.py
> +        # Packaging can be sold even if the packaging type does not allows it
```suggestion
        # Packaging can be sold even if the packaging level does not allows it
```

2023-07-28 05:04 UTC, QuocDuong1306 commented
Hi @nilshamerlinck , I updated

2023-07-28 08:04 UTC, nilshamerlinck approved these changes

2024-03-12 08:07 UTC, merged